### PR TITLE
Update Mocha link

### PR DESCRIPTION
**Pull request by mortonfox**

### CODE REVIEW

**Comment by charneykaye** [comment]
Thanks!

**Comment by charneykaye** [comment]
Hiya @mortonfox please note that the URL her is turning up a 404 atm. Please advise, thanks.

**Comment by mortonfox** [comment]
It is working for me. Try a curl -I at your end to test it:

```
$ curl -I http://mochajs.org/
HTTP/1.1 200 OK
Date: Tue, 02 May 2017 20:15:54 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=d9c15867242da66947d6a7303e292684f1493756154; expires=Wed, 02-May-18 20:15:54 GMT; path=/; domain=.mochajs.org; HttpOnly
Last-Modified: Sun, 15 Jan 2017 12:32:11 GMT
Access-Control-Allow-Origin: *
Expires: Tue, 02 May 2017 20:25:54 GMT
Cache-Control: max-age=600
X-GitHub-Request-Id: 87A2:34AF:23040:30F32:5908E8FA
Server: cloudflare-nginx
CF-RAY: 358da7c0a4dd0f1b-IAD
```

**Comment by charneykaye** [comment]
PEBKAC, I was testing the old URL. Should have been sleeping instead of staying up late! Thanks again.

**Pull request merged**
